{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "1.21.8-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.8-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.2"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.8-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.8-R0.1-SNAPSHOT.jar",
          "size": 2716015,
          "sha512": "38cb4b8faf3d8fe1fc673324d10dcf5320117aaaf7b781fcf3752c6a6e10e984279f4a0ad7ecbddf8c84714d426964a9639205a57c9326087d03bbdf8b6a064b",
          "sha256": "2743e4c0f554733c6c49b16aa43d0fd8e10b2ed63d853bba64b812fdb42ced5f",
          "sha1": "7e6f95195b47f2887046b3baaf310ae9a8031845",
          "md5": "f6db6f95e9d20c4a600b373e7c1a5bbc"
        }
      ],
      "capabilities": [
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.8-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.8-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.24.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.8-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.8-R0.1-SNAPSHOT.jar",
          "size": 2716015,
          "sha512": "38cb4b8faf3d8fe1fc673324d10dcf5320117aaaf7b781fcf3752c6a6e10e984279f4a0ad7ecbddf8c84714d426964a9639205a57c9326087d03bbdf8b6a064b",
          "sha256": "2743e4c0f554733c6c49b16aa43d0fd8e10b2ed63d853bba64b812fdb42ced5f",
          "sha1": "7e6f95195b47f2887046b3baaf310ae9a8031845",
          "md5": "f6db6f95e9d20c4a600b373e7c1a5bbc"
        }
      ],
      "capabilities": [
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.8-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.8-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.8-R0.1-SNAPSHOT-sources.jar",
          "url": "folia-api-1.21.8-R0.1-SNAPSHOT-sources.jar",
          "size": 1950209,
          "sha512": "89403133b471ccf252834cb8c636b7e3e8d55a4483213d6f4cfcce5f29f8c6dcf8c6dfb975c07acfe060df792cccaeab92552a6be3631284ba5e485a992079af",
          "sha256": "eda1c4ca1f1920597a959c3a9490613bc9dec9af7bf72b32053f5090e5d8d1bd",
          "sha1": "0f9e9b00db21437a86be473decf4e2cab29c2c3a",
          "md5": "731e19fd09f7f5edebafcfbfe1228b40"
        }
      ],
      "capabilities": [
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.8-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.8-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.8-R0.1-SNAPSHOT-javadoc.jar",
          "url": "folia-api-1.21.8-R0.1-SNAPSHOT-javadoc.jar",
          "size": 15736283,
          "sha512": "e4e09db98983ebd4e958576eb9575f8e66915c4494dc21f2943ee9452abdda44e32d451d4e935ae511bfe33ce70f7183dba141d9182362129562a194a911b341",
          "sha256": "153118b41808d263b9ec77c237159dc8c6d0546e15ded66c868e9d731ae22590",
          "sha1": "e9b3541ea36261078f9b9cc1f4afa9726f555087",
          "md5": "6585434e92b57637ce11651d6c1928e3"
        }
      ],
      "capabilities": [
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.8-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.8-R0.1-SNAPSHOT"
        }
      ]
    }
  ]
}
