{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "1.21.11-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.2"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "size": 2805103,
          "sha512": "4ee18b75eebe93d404d7b3d44fc65813daa35fb3f4d03eea79f6927d9b49924238abb8c5aecc95cabc928d86730b96bf6f82947ebc905ab3dd040b1e2affa8fe",
          "sha256": "910fdc9ca7b0cb95e3897503f58ca66a6bdab2b47de5326dd55fbe84355a621c",
          "sha1": "f4e7cc98ac90fcb34a27abde7e3450ca93966fa1",
          "md5": "3030b6033c524a9f216a9662fb558421"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "size": 2805103,
          "sha512": "4ee18b75eebe93d404d7b3d44fc65813daa35fb3f4d03eea79f6927d9b49924238abb8c5aecc95cabc928d86730b96bf6f82947ebc905ab3dd040b1e2affa8fe",
          "sha256": "910fdc9ca7b0cb95e3897503f58ca66a6bdab2b47de5326dd55fbe84355a621c",
          "sha1": "f4e7cc98ac90fcb34a27abde7e3450ca93966fa1",
          "md5": "3030b6033c524a9f216a9662fb558421"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT-sources.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT-sources.jar",
          "size": 2002885,
          "sha512": "e1c84fa986312a696ed6f439eb3ee9915f515ae7ca0ebf07c6b47fa785bb26e1e24cace10eb6c5e20c3fa6067b1cbc590ebcfb2310c54b00901cfefaa24f6f9d",
          "sha256": "153cf91e9beceada98dd5905e605c9609a77e0afd0ad798627304a98ee570160",
          "sha1": "efe201af25882ddad026dada29350fbd67772cfd",
          "md5": "d8515c728d130893b0d4d1a20f99a67c"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT-javadoc.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT-javadoc.jar",
          "size": 16197197,
          "sha512": "a970a5bc86455bed37e737d81e20d6d6d1a2011d04abe46086d1c386290c3875f8b335b728267bbb60ee923601f4cc906c4a4ad1cf93ea63d3824c6024c0f9df",
          "sha256": "cc34bac50d15c4b4f988e4a41042d064c83b8f6eaa0b83f52a9697b13cdf8101",
          "sha1": "0a7d9655bb309c632a524099535ab189e227fa86",
          "md5": "b1a828be321a0503c9248b74eb758561"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    }
  ]
}
