{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "1.21.11-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.2"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "size": 2805298,
          "sha512": "f0e81cc98ae3da4f8af325598ff1efb693b1f0bd83a71c9cd6bcb37cf70b32a23d78e77646037a73a858d2b2d6900c8bc5e764e07fa591ff3c1cd28af26b1d25",
          "sha256": "b0f47989fc11e62a25d3cceb1f6c647e701e6224e17fbecfa10267ec4a9194a7",
          "sha1": "a5f9dbb7fbf21c47bc2b7800fbced368af0e08f6",
          "md5": "77304789bbdad1189d0dd72a313ee98a"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT.jar",
          "size": 2805298,
          "sha512": "f0e81cc98ae3da4f8af325598ff1efb693b1f0bd83a71c9cd6bcb37cf70b32a23d78e77646037a73a858d2b2d6900c8bc5e764e07fa591ff3c1cd28af26b1d25",
          "sha256": "b0f47989fc11e62a25d3cceb1f6c647e701e6224e17fbecfa10267ec4a9194a7",
          "sha1": "a5f9dbb7fbf21c47bc2b7800fbced368af0e08f6",
          "md5": "77304789bbdad1189d0dd72a313ee98a"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT-sources.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT-sources.jar",
          "size": 2003135,
          "sha512": "a729b2326dfd549252d811d689f2eba85d46e61d9675745419796c53f992bcd4ccf8f819e65969fc90b57117797bede42d3fb9feca2b72f72638e9559e369f1e",
          "sha256": "f49ea81731d99497234ed3cc4e3234334238c00c71be189bb1db5fc608b03b04",
          "sha1": "3c60c866d5549b70b092a3b018d8dd97320a8ce5",
          "md5": "1598363b398fd1c9efe32ff69b0ab764"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:1.21.11-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.11-R0.1-SNAPSHOT-javadoc.jar",
          "url": "folia-api-1.21.11-R0.1-SNAPSHOT-javadoc.jar",
          "size": 16198336,
          "sha512": "ba1f3896aba05d5c02412bf79bc0f0e610e28a7ac61d76750738b2bab13607e85131c3c86968e67c2b1ef88966809502286b9334b875360e40be6e0081ca5236",
          "sha256": "6256c86d9cabcf3209291d979226df53a2e4008d12cbb321c33e0ec90bc2715c",
          "sha1": "fba732a075a23f51440e5bd3ec4cb615304c7c30",
          "md5": "27ec100d662d3984361f79adb465521d"
        }
      ],
      "capabilities": [
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.11-R0.1-SNAPSHOT"
        }
      ]
    }
  ]
}
