{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "dev-bundle",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "devBundle",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "zip"
      },
      "files": [
        {
          "name": "dev-bundle-unspecified.zip",
          "url": "dev-bundle-unspecified.zip",
          "size": 25681920,
          "sha512": "15871e3c17b9f9854af7b6b45b4db6bbc7250587e6e87e124f467f47666aa4f9c16d31769589d6860ea5b6b37add52419c920472448460be39e4b2d042c185b9",
          "sha256": "497392767fa1e75fa087b6c824518c7322957230e1aafd83fca1a134285078bb",
          "sha1": "6fa3c82dc2f92ea1bfba73dc510fc5643bcd7bb4",
          "md5": "eaad137503c37572b24a82411d6b4b5e"
        }
      ]
    },
    {
      "name": "serverRuntimeClasspath",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "serverDependencies",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.49.1.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "com.lmax",
          "module": "disruptor",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "dev.folia",
          "module": "folia-api",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ca.spottedleaf",
          "module": "concurrentutil",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-ffm",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jni",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-native",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-haproxy",
          "version": {
            "requires": "4.2.7.Final"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.lucko",
          "module": "spark-api",
          "version": {
            "requires": "0.1-20240720.200737-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-paper",
          "version": {
            "requires": "1.10.152"
          }
        },
        {
          "group": "io.papermc",
          "module": "mache",
          "version": {
            "requires": "26.1.2+build.1"
          }
        }
      ]
    },
    {
      "name": "serverCompileClasspath",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "serverDependencies",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.folia",
          "module": "folia-api",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "ca.spottedleaf",
          "module": "concurrentutil",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-ffm",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jni",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-native",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-haproxy",
          "version": {
            "requires": "4.2.7.Final"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.lucko",
          "module": "spark-api",
          "version": {
            "requires": "0.1-20240720.200737-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-paper",
          "version": {
            "requires": "1.10.152"
          }
        },
        {
          "group": "io.papermc",
          "module": "mache",
          "version": {
            "requires": "26.1.2+build.1"
          }
        }
      ]
    }
  ]
}
