{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:unspecified",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.2"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-unspecified.jar",
          "url": "folia-api-unspecified.jar",
          "size": 2832834,
          "sha512": "211db883399b03d759e2cd8c0c16d6fd604824ba7c57991d63ff6763c9ba19b5ecb14ddb19f4ba763b00b5c3c06f915e26a4c660c17b56f2422723915e3051f9",
          "sha256": "1e0f295ee7f3ba5440187b6bcfad931451d23671c3101da3306614dd1c2f7680",
          "sha1": "2c852d193c1256be72796b60468f956744af4278",
          "md5": "859d786f2b576f5a346ba4a091f5a86f"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "unspecified"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "unspecified"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "unspecified"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "unspecified"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:unspecified",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "folia-api-unspecified.jar",
          "url": "folia-api-unspecified.jar",
          "size": 2832834,
          "sha512": "211db883399b03d759e2cd8c0c16d6fd604824ba7c57991d63ff6763c9ba19b5ecb14ddb19f4ba763b00b5c3c06f915e26a4c660c17b56f2422723915e3051f9",
          "sha256": "1e0f295ee7f3ba5440187b6bcfad931451d23671c3101da3306614dd1c2f7680",
          "sha1": "2c852d193c1256be72796b60468f956744af4278",
          "md5": "859d786f2b576f5a346ba4a091f5a86f"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "unspecified"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "unspecified"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "unspecified"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "unspecified"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:unspecified",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-unspecified-sources.jar",
          "url": "folia-api-unspecified-sources.jar",
          "size": 2017568,
          "sha512": "ef2f184d6262659914442c7806cd5d367cbea55c4aa095771814a8c6ca64279f84220facbf04940e19e444610073058f9edf7f42694236701c2ff1264b1a4bcf",
          "sha256": "703e7e9cd436a7fcd25409b299e843a08cdd945ea4731916a04b5f1456f43627",
          "sha1": "7a948161c55942e9960ff5451e995b62056e4cc1",
          "md5": "c9dea3555429983729564b24a8e60c6a"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "unspecified"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "unspecified"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "unspecified"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "unspecified"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:unspecified",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-unspecified-javadoc.jar",
          "url": "folia-api-unspecified-javadoc.jar",
          "size": 21341722,
          "sha512": "1030956dba4272511be30d7b0b48d4a123339391fecfbe078e5fe4275700f21e13cae9d07c1471aeda6a0cf65aa77f5111e24df0eae0423b9ecb521b1d2db8e0",
          "sha256": "c8d0d14e4f17a57f17ba96e6ced19dc0947e524f6802d6d18190cd370afe2ce7",
          "sha1": "e5bbd877a9d4964a985c5bffe35d1f014bcf75df",
          "md5": "3dd2938aeb41a2584d78561992f2d0da"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "unspecified"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "unspecified"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "unspecified"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "unspecified"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "unspecified"
        }
      ]
    }
  ]
}
