{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "dev-bundle",
    "version": "26.2.local-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "devBundle",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "zip"
      },
      "files": [
        {
          "name": "dev-bundle-26.2.local-SNAPSHOT.zip",
          "url": "dev-bundle-26.2.local-SNAPSHOT.zip",
          "size": 26007600,
          "sha512": "4c6a32e83c997ca827e11c55be03d3a66a32b4cf36781dd1b6634bd64af934dce41d3f6369639385c17bb8d9f2474bada025739887a022b625b740e9282e07f1",
          "sha256": "4318513f6ceee135c3cb486b4fc18a8e95fc61602ca762cce108a5c70b14ded9",
          "sha1": "0125773ef7d54e78102129228e5e14d8cba2ac38",
          "md5": "60d77f67bd6121d0a049c17c7ceb9814"
        }
      ]
    },
    {
      "name": "serverRuntimeClasspath",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "serverDependencies",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.49.1.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "com.lmax",
          "module": "disruptor",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "dev.folia",
          "module": "folia-api",
          "version": {
            "requires": "26.2.local-SNAPSHOT"
          }
        },
        {
          "group": "ca.spottedleaf",
          "module": "leafpile",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-ffm",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jni",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-native",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-haproxy",
          "version": {
            "requires": "4.2.15.Final"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.lucko",
          "module": "spark-api",
          "version": {
            "requires": "0.1-20240720.200737-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-paper",
          "version": {
            "requires": "1.10.172"
          }
        },
        {
          "group": "io.papermc",
          "module": "mache",
          "version": {
            "requires": "26.2+build.1"
          }
        }
      ]
    },
    {
      "name": "serverCompileClasspath",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "serverDependencies",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.folia",
          "module": "folia-api",
          "version": {
            "requires": "26.2.local-SNAPSHOT"
          }
        },
        {
          "group": "ca.spottedleaf",
          "module": "leafpile",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-ffm",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jni",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-native",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-haproxy",
          "version": {
            "requires": "4.2.15.Final"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9.1"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.lucko",
          "module": "spark-api",
          "version": {
            "requires": "0.1-20240720.200737-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-paper",
          "version": {
            "requires": "1.10.172"
          }
        },
        {
          "group": "io.papermc",
          "module": "mache",
          "version": {
            "requires": "26.2+build.1"
          }
        }
      ]
    }
  ]
}
