{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "26.2.local-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:26.2.local-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "5.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-key"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.2"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-26.2.local-SNAPSHOT.jar",
          "url": "folia-api-26.2.local-SNAPSHOT.jar",
          "size": 2886504,
          "sha512": "92ecb8b0a0dfefec867c4abc7480c4cec730b10442a537a4532f9fb52f1787024960a1311596adf7d6cf3769332db71596e49769b4defacde138978787911829",
          "sha256": "9016434a86d08c1a0b732c958b7cee1840e35a0c4bff0ad01c3a18d94bb1617f",
          "sha1": "9b0fd162adfc926badf8f75012a0dfbf54e18ae9",
          "md5": "00c20311ed572ffc0848023edcad6bc9"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:26.2.local-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.6.0-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.18"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.26.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "5.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-key"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-26.2.local-SNAPSHOT.jar",
          "url": "folia-api-26.2.local-SNAPSHOT.jar",
          "size": 2886504,
          "sha512": "92ecb8b0a0dfefec867c4abc7480c4cec730b10442a537a4532f9fb52f1787024960a1311596adf7d6cf3769332db71596e49769b4defacde138978787911829",
          "sha256": "9016434a86d08c1a0b732c958b7cee1840e35a0c4bff0ad01c3a18d94bb1617f",
          "sha1": "9b0fd162adfc926badf8f75012a0dfbf54e18ae9",
          "md5": "00c20311ed572ffc0848023edcad6bc9"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:26.2.local-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-26.2.local-SNAPSHOT-sources.jar",
          "url": "folia-api-26.2.local-SNAPSHOT-sources.jar",
          "size": 2051303,
          "sha512": "1ea5a66084d10e599b20f31d440abf3eda39e788217f0029f2f73e4751f951bb3f528689c3ad356edc70003c21efb151baa4540d90fc34eabca2b488140c6e51",
          "sha256": "c1370f68acc671dde3ebb10fafc988a07ac3026ac046f0040440f329b1cbd935",
          "sha1": "b86f795466f9210d3e5ef8f270b95f311a191b37",
          "md5": "8cb7ab3d01f20ba7ddbb8666cb1377d2"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "dev.folia:folia-api:26.2.local-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-26.2.local-SNAPSHOT-javadoc.jar",
          "url": "folia-api-26.2.local-SNAPSHOT-javadoc.jar",
          "size": 21762085,
          "sha512": "0fc1b769d650355b1161ff44320934b67c320238dab4c1634dff0500f9dd2972b7e0d068eb24e3e3caffb673ec0ffd6276c7515f875256468e6879df65818931",
          "sha256": "854f915a33b727766e7a434ca44551e0fdbd4e9fff7042dae51307c13996bdeb",
          "sha1": "aa1a55a3367f1ac7e96e0b00b082a05d6620c2a0",
          "md5": "7500bd5598b29d1c6132770cd2a60572"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.2.local-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.2.local-SNAPSHOT"
        }
      ]
    }
  ]
}
