{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "dev-bundle",
    "version": "1.21.11-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "devBundle",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "zip"
      },
      "files": [
        {
          "name": "dev-bundle-1.21.11-R0.1-SNAPSHOT.zip",
          "url": "dev-bundle-1.21.11-R0.1-SNAPSHOT.zip",
          "size": 27533790,
          "sha512": "4e171dabca84814dc5a16266408866341d7d8eea8ea8eabf9fb2ebe77d9103de8108b49ae449cb54ba924a7cda2db8eccf3c3f02f18e7c740a519bb742940a02",
          "sha256": "1b02e15a71b9a4beeeac9383572ab059a36b9e27d9b573aa8731bc67c9d3ad5d",
          "sha1": "40672277ccee2ccde2f454c981a8beaa2071f11b",
          "md5": "68fa3c9e2eeae3f186bbf5a975fbb7a0"
        }
      ]
    },
    {
      "name": "serverRuntimeClasspath",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "serverDependencies",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.49.1.0"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j",
          "version": {
            "requires": "9.2.0"
          }
        },
        {
          "group": "com.lmax",
          "module": "disruptor",
          "version": {
            "requires": "3.4.4"
          }
        },
        {
          "group": "dev.folia",
          "module": "folia-api",
          "version": {
            "requires": "1.21.11-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "ca.spottedleaf",
          "module": "concurrentutil",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-ffm",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jni",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-native",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-haproxy",
          "version": {
            "requires": "4.2.7.Final"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "net.neoforged",
          "module": "AutoRenamingTool",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.papermc",
          "module": "reflection-rewriter",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "io.papermc",
          "module": "reflection-rewriter-runtime",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "io.papermc",
          "module": "reflection-rewriter-proxy-generator",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-api",
          "version": {
            "requires": "0.1-20240720.200737-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-paper",
          "version": {
            "requires": "1.10.152"
          }
        },
        {
          "group": "io.papermc",
          "module": "mache",
          "version": {
            "requires": "1.21.11+build.1"
          }
        }
      ]
    },
    {
      "name": "serverCompileClasspath",
      "attributes": {
        "io.papermc.paperweight.dev-bundle-output": "serverDependencies",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.folia",
          "module": "folia-api",
          "version": {
            "requires": "1.21.11-R0.1-SNAPSHOT"
          }
        },
        {
          "group": "ca.spottedleaf",
          "module": "concurrentutil",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-ffm",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "org.jline",
          "module": "jline-terminal-jni",
          "version": {
            "requires": "3.27.1"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-ansi"
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "com.velocitypowered",
          "module": "velocity-native",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-codec-haproxy",
          "version": {
            "requires": "4.2.7.Final"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-iostreams",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "net.neoforged",
          "module": "AutoRenamingTool",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.papermc",
          "module": "reflection-rewriter",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "io.papermc",
          "module": "reflection-rewriter-runtime",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "io.papermc",
          "module": "reflection-rewriter-proxy-generator",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-api",
          "version": {
            "requires": "0.1-20240720.200737-2"
          }
        },
        {
          "group": "me.lucko",
          "module": "spark-paper",
          "version": {
            "requires": "1.10.152"
          }
        },
        {
          "group": "io.papermc",
          "module": "mache",
          "version": {
            "requires": "1.21.11+build.1"
          }
        }
      ]
    }
  ]
}
