{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.folia",
    "module": "folia-api",
    "version": "1.21.1-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.20-R0.2-deprecated+build.18"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.6"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.1-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.1-R0.1-SNAPSHOT.jar",
          "size": 2344682,
          "sha512": "059cb6748bfe702d2ac91d12106d2ac2395852d161964a31e8b9fca3cd7e9f5d9a15efaad85916d89a23c9a4fa214a86319870a1050e898618dd53b27453b9dc",
          "sha256": "06f182fe91682df2220716f9d96590630427f0385f92ffe64a99385a30effe74",
          "sha1": "9ba2fe26af58de2ac9dbf1f986d74f9d9dfdda56",
          "md5": "40569ec24244780060fd2d306113f2f2"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.20-R0.2-deprecated+build.18"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.5"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.6"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.17.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "folia-api-1.21.1-R0.1-SNAPSHOT.jar",
          "url": "folia-api-1.21.1-R0.1-SNAPSHOT.jar",
          "size": 2344682,
          "sha512": "059cb6748bfe702d2ac91d12106d2ac2395852d161964a31e8b9fca3cd7e9f5d9a15efaad85916d89a23c9a4fa214a86319870a1050e898618dd53b27453b9dc",
          "sha256": "06f182fe91682df2220716f9d96590630427f0385f92ffe64a99385a30effe74",
          "sha1": "9ba2fe26af58de2ac9dbf1f986d74f9d9dfdda56",
          "md5": "40569ec24244780060fd2d306113f2f2"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.1-R0.1-SNAPSHOT-sources.jar",
          "url": "folia-api-1.21.1-R0.1-SNAPSHOT-sources.jar",
          "size": 1706464,
          "sha512": "a499de209259f83ab2031fe8f981a393aebf520fd6952ddce8531d559574249e05e03f199d1d995ce7ee07f4601aade2282592ec07cb099c22fb07b0f92dbea6",
          "sha256": "cb597b618b843456c8e59719b87b4f147b01a83f5063bb44b9caabe707649e1e",
          "sha1": "8bce3f849104295c9521f3ddff3458dcd0178389",
          "md5": "8e356ec7b184f315805bfb3c7c868e9e"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "folia-api-1.21.1-R0.1-SNAPSHOT-javadoc.jar",
          "url": "folia-api-1.21.1-R0.1-SNAPSHOT-javadoc.jar",
          "size": 13485600,
          "sha512": "ac91ebf386887be0941c3394d893b3707bde6c794f088eee1bd686d82848b80951b93c5e8787aa0f383f48f0f49f2256146af4b5e809183a558f2ac2180d21b5",
          "sha256": "5e4292e428b874b10e56a3ca7cc11df782d3432dc25409d8012e162b6f1851a3",
          "sha1": "32378db3f63eed977209afb37b2fd7be35ada1ba",
          "md5": "c42fca069c31f4daf2971d87a96c45d1"
        }
      ],
      "capabilities": [
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "dev.folia",
          "name": "folia-api",
          "version": "1.21.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "1.21.1-R0.1-SNAPSHOT"
        }
      ]
    }
  ]
}
